- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: double-quote-string-fixer

- repo: local
  hooks:

  - id: yapf
    name: yapf
    entry: yapf
    language: system
    types: [python]
    args: ['-i']
    exclude: &exclude_files >
      (?x)^(
        aiida_codtools/calculations/cif_cod_deposit.py|
        aiida_codtools/parsers/cif_cod_deposit.py|
        docs/.*|
      )$

  - id: prospector
    language: system
    types: [file, python]
    exclude: *exclude_files
    name: prospector
    description: 'This hook runs Prospector: https://github.com/landscapeio/prospector'
    entry: prospector

  - id: version-number
    name: Check consistency in version number
    entry: python ./.ci/validate_version_number.py
    language: system
    files: '^(setup.json)'
    pass_filenames: false

- repo: https://github.com/python-modernize/python-modernize.git
  sha: a234ce4e185cf77a55632888f1811d83b4ad9ef2
  hooks:
  - id: python-modernize
    exclude: ^docs/
    args:
      - --write
      - --nobackups
