- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: double-quote-string-fixer

- repo: local
  hooks:

  - id: yapf
    name: yapf
    entry: yapf
    language: system
    types: [python]
    args: ['-i']
    exclude: &exclude_files >
      (?x)^(
        docs/.*|
      )$

  - id: prospector
    name: prospector
    description: 'Run prospector'
    language: system
    types: [file, python]
    exclude: *exclude_files
    entry: prospector

  - id: version-number
    name: Check consistency in version number
    entry: python ./utils/validate_version_number.py
    language: system
    files: '^(setup.json)'
    pass_filenames: false

- repo: https://github.com/python-modernize/python-modernize.git
  rev: a234ce4e185cf77a55632888f1811d83b4ad9ef2
  hooks:
  - id: python-modernize
    exclude: ^docs/
    args:
      - --write
      - --nobackups
