dist: xenial
sudo: required

language: python
cache: pip

python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7

services:
    - postgresql

addons:
    postgresql: 9.6
    apt:
        update: true

before_install:
    - sudo apt install rabbitmq-server
    - pip install -U pip wheel setuptools reentry numpy==1.16.4

install:
    - pip install .[dev,docs]
    - reentry scan

env:
    - TEST_TYPE="pre-commit"
    - TEST_TYPE="tests"

script:
    - if [ "$TEST_TYPE" == "tests" ];then pytest tests ;fi
    - if [ "$TEST_TYPE" == "pre-commit" ];then pre-commit install; pre-commit run --all-files || ( git status --short; git diff ; exit 1 ); fi

git:
    depth: 3
