dist: trusty
sudo: required

language: python

python:
    - "2.7"
    - "3.6"

cache: pip

services:
    - rabbitmq
    - postgresql

addons:
    postgresql: "9.6"

before_install:
    - pip install -U pip==18.1 wheel setuptools reentry

install:
    - pip install .[dev,docs]

env:
    - TEST_TYPE="pre-commit"

script:
    - if [ "$TEST_TYPE" == "pre-commit" ] ; then pre-commit install; pre-commit run --all-files || ( git status --short; git diff ; exit 1 ); fi

git:
  depth: 3
